# Generated by Django 3.0.8 on 2020-10-05 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='console',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_console', models.CharField(max_length=100)),
                ('release_date_console', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_developer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_date_game', models.DateField(blank=True, null=True)),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_arawato.console')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_arawato.developer')),
            ],
        ),
    ]
